### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-swift#12]
Hi there,

I'm wondering if there is a open source license for this project? Thanks.
BTW, I tried to use https://github.com/cisco-sso/velero-plugin-openstack on my project but it seems to be not maintained any longer and it is not supported by the latest version of velero as well. Therefore, I'd like to know if this plugin is compatible with the latest version of velero?
Besides, would you mind telling me the time of cinder block storage could be supported? I noticed you've already created a PR for this. Really appreciate for your patience.

**Comment by Lirt** [comment]
Hi @AlwaySummit,

I didn't include license for this project, but if there is one it will be one of the permissive ones. I need to take a look at them.

I am using the plugin with velero `v1.5.2` (`1.5.3` is latest). So far no breaking changes were made since I released so it should work with 1.4 and newer. 

Regarding the block storage I wanted to prepare repeatable local testing environment, because it takes too much time for me to test the code. This is pretty complicated due to a nature of Openstack and local deployment options (so far I think [openstack-helm](https://github.com/openstack/openstack-helm) could be the way).

Hard to say about the timeline. I will try to review it again but I cannot promise anything right now.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Thanks for your prompt response. That would be kind of you if you could add a license for this project which is indispensable from my side. I just want you know that I don't mean to press you but take your time. Besides, I can do some relevant work if you need any help. Thanks for your implication again.

**Comment by Lirt** [comment]
Does this suit your needs? It's MIT License one of the permissive ones.
https://github.com/Lirt/velero-plugin-swift/pull/13

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Sure. Appreciate it.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Could you please create a new tag that contains the latest changes so that I'm able to download the artifact in my code automatically? Thanks.

**Comment by Lirt** [comment]
Does it need to be included? It's just repository artifact and there is no reason to make release because of it.

**Comment by AlwaySummit** [comment]
I got it. Thanks! I'll try to find another way out.
