### ISSUE TITLE
"Temp URL invalid" error when uploading backups to swift

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-swift#14]
Hi @Lirt 
Currently, I'm doing some testing about backup&restore and facing an error when uploading backups to swift. I'm trying to investigate but still no clues so I'd like to ask for help if you have time on this. Thanks in advance.

**Environment**
velero: 1.4.0
velero-plugin-swift: latest code
OS variable I set:
- OS_AUTH_URL
- OS_USERNAME
- OS_PASSWORD
- OS_REGION_NAME
- OS_PROJECT_NAME
- OS_PROJECT_ID
- OS_DOMAIN_ID

**Symptom**
Basically, there are three kinds of phenomena after executing 'velero backup create xxx'.

- Failed. 
- ![image](https://user-images.githubusercontent.com/20851530/111316235-0dd5c400-869e-11eb-80c2-02ab1ef53a76.png)
- PartiallyFailed
- ![image](https://user-images.githubusercontent.com/20851530/111316775-8177d100-869e-11eb-9f23-9123e7235b96.png)
- Completed
- ![image](https://user-images.githubusercontent.com/20851530/111316967-ac622500-869e-11eb-8d20-36499af95a75.png)

The weird thing is if you execute 'velero backup logs' to check the log message, it shows identical content even the Completed one. The log shows below.
![image](https://user-images.githubusercontent.com/20851530/111317268-f519de00-869e-11eb-92dc-fdbc3074fb56.png)

**Reproduce procedure**

1. Set OS variables aforementioned.
2. Execute velero backup create xxx.
3. Wait for a while and execute velero backup logs xxx.

**Comment by Lirt** [comment]
Hello @AlwaySummit,

first let me ask you if you set the Temp-Url-Key. I think this needs to be set in the swift account in order to generate temp-url (I'm not 100% sure right now but I can double-check later). You can do it with command such as `swift post -m "Temp-URL-Key:my-special-key"`. 

- Here are official [docs]( https://docs.openstack.org/swift/latest/api/temporary_url_middleware.html) for it.
- Swiftstack also [requires this](https://www.swiftstack.com/docs/admin/middleware/tempurl.html#setting-the-key).

If your plugin version is newer than [this commit](https://github.com/Lirt/velero-plugin-swift/commit/b4e4cc607746958952b9a9771f6dd3582cac0a8c), it should be fine. But in older version there was [Temp-URL bug](https://github.com/gophercloud/gophercloud/issues/1993) I discovered and fixed in upstream.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

It's resolved after I set the Temp-Url-Key. Thanks for your time.
